COLORS = {"white": (255, 255, 255), "red": (255, 0, 0)}

MAZE_SIDE_CELL_AMOUNT = 10

CELL_SIZE = 40

WIDTH = MAZE_SIDE_CELL_AMOUNT * CELL_SIZE
HEIGHT = MAZE_SIDE_CELL_AMOUNT * CELL_SIZE

MAP_NET_WIDTH = 7
